#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."


docker run -it --name=ha --rm -p 8123:8123 --pull always -v ./custom_components:/config/custom_components:ro -v ./.haconfig:/config homeassistant/home-assistant:stable